Adicionando a tabela curso.sql
Lvght/e-andifes pull request #13
Opened 2023-08-02 15:47 UTC by thaleswinther

2023-08-02 16:48 UTC, leonardo-lopes-br submitted a review, later dismissed

2023-08-02 18:45 UTC, leonardo-lopes-br approved these changes

2023-08-02 19:34 UTC, Kommnenos submitted a review, later dismissed

2023-08-02 19:47 UTC, leonardo-lopes-br approved these changes

2023-08-02 20:04 UTC, CarlosFontaneli approved these changes

2023-08-02 20:24 UTC, LucasMBalieiro approved these changes

2023-08-02 20:27 UTC, Kommnenos approved these changes

2023-08-02 20:34 UTC, arisaabiko approved these changes

2023-08-03 00:05 UTC, Lvght requested changes
Os testes não estão passando de verdade, é preciso fazer rebase novamente a partir da nossa main.

Na imagem podemos ver que o teste não opera como esperado:

![image](https://github.com/Lvght/e-andifes/assets/28585648/65ca7ec4-257f-47e6-8175-814ab9e36224)

Além disso, algumas tabelas possuem erros de sintaxe com a cláusula `IF NOT EXISTS` ou pequenos erros como dois `NOT`s seguidos.

Em consideração disso, peço que:

- as alterações do main do repositório principal sejam aplicadas neste repositório;
- os erros de sintaxe sejam corrigidos; e
- o conflito no arquivo de criação de tabelas seja resolvido.

2023-08-03 23:08 UTC, closed without merging