Create disciplinaespecializacao.sql
Lvght/e-andifes pull request #14
Opened 2023-08-02 16:53 UTC by Kommnenos

2023-08-02 18:09 UTC, leonardo-lopes-br approved these changes

2023-08-02 19:37 UTC, Alynva submitted a review, later dismissed

2023-08-02 20:15 UTC, Mobuos submitted a review, later dismissed

2023-08-02 20:21 UTC, JonathanBDias approved these changes

2023-08-02 20:22 UTC, Mobuos submitted a review, later dismissed

2023-08-02 20:49 UTC, Alynva requested changes
@Kommnenos faltou adicionar a tabela no `__create.txt`, na ordem "correta" (entes de algo que usa ela). Vou deixar os commits que eu fiz para forçar o erro, para vermos o teste reclamar corretamente

2023-08-03 00:40 UTC, Lvght requested changes

2023-08-03 00:40 UTC, Lvght commented on sql/disciplina_especializacao.sql
> +    tipo_disciplina VARCHAR(100) NOT NULL,
Esse `tipo` pode ser qualquer coisa ou apenas alguns valores específicos? Se forem valores específicos, precisamos colocar isso como um ENUM. Igual fizemos com gênero.

Crie um tipo `CATEGORIA_DISCIPLINA_ESPECIALIZACAO` assim como no exemplo abaixo e use esse tipo ao invés de `VARCHAR(100)`.

https://github.com/Lvght/e-andifes/blob/3a9fde3bf7d862754484fef574f9dde47326f979/sql/__tipos.sql#L3

2023-08-04 20:46 UTC, Kommnenos commented on sql/disciplina_especializacao.sql
> +    tipo_disciplina VARCHAR(100) NOT NULL,
Ninguém conseguiu descobrir o que tipo_disciplina significa, então no fim acho que pode ser descartada.

2023-08-08 14:32 UTC, Lvght commented
# O que falta para fechar essa PR

- Resolver os conflitos com a main
- Garantir que os testes estão passando
- Validar o diagrama do banco de dados. Temos 47 tabelas na `main` e não podemos ter menos que isso para aprovar essa PR. Afinal, isso indicaria algum erro que os testes não pegaram

Além disso, a `carga_horaria` realmente seria um `varchar`? Perguntando por desconhecer o que vamos armazenar nesse campo.

2023-08-08 15:39 UTC, Lvght approved these changes
LGTM

2023-08-08 15:42 UTC, NataliaBachiega approved these changes

2023-08-08 15:42 UTC, merged