Adicionando tabelas gestor_oferta e turma_disciplina_especializacao
Lvght/e-andifes pull request #15
Opened 2023-08-02 18:31 UTC by CarlosFontaneli

Adicionando 2 tabelas do usuario 3, a tabelas disciplina_especializacao nao é nossa, implementamos pois dependemos do ID dela

2023-08-02 18:44 UTC, Mobuos approved these changes
Nenhum erro encontrado nos logs
CONFIO

2023-08-02 20:00 UTC, thaleswinther approved these changes

2023-08-03 00:49 UTC, Lvght approved these changes
![image](https://github.com/Lvght/e-andifes/assets/28585648/d5d63138-3f63-4591-88b6-a570748f772d)

Estas duas tabelas estão flutuando no diagrama. Deveria estar assim mesmo?

2023-08-03 00:51 UTC, Lvght reviewed
...

2023-08-03 00:52 UTC, Lvght requested changes
(aprovei sem querer, foi mal)

as tabelas do comentário acima na conversa realmente deveriam estar soltas daquele jeito?

2023-08-04 21:43 UTC, Lvght approved these changes
LGTM!

2023-08-04 21:44 UTC, merged