adicionando 4 tabelas
Lvght/e-andifes pull request #3
Opened 2023-08-02 03:03 UTC by gabscastilho

tabelas: cursista, material, repositorioCursista, orientadorOrientaCursista

2023-08-02 13:11 UTC, Lvght commented on sql/aluno_comunidade_academica.sql
> +    genero                  char(1)     NOT NULL,
Temos um tipo customizado para gênero (`GENERO`) que atua como um enumerador, impedindo o cadastro de valores inválidos. Só estou pontuando isso porque entendo que deve ser estranho ver o tipo `GENERO`, mas ele é definido aqui:

https://github.com/Lvght/e-andifes/blob/ae9d597b12401bcd6fd0a94efbd54056dc2b7566/sql/__tipos.sql#L3

Se ainda assim acharem mais prudente modificar para `char`, sem problemas.

2023-08-02 14:30 UTC, Lvght requested changes
![image](https://github.com/Lvght/e-andifes/assets/28585648/700acfa4-ec20-49aa-b62b-ce57839eb48c)

Pessoal, não consegui subir o banco aqui na minha máquina. Aparentemente existem alguns erros. Poderiam dar uma investigada?

Lembrando que se alguém ainda tiver problemas para subir o ambiente, rodem na branch de vocês:

```
git rebase main
```

2023-08-02 15:27 UTC, KY-U commented on sql/aluno_comunidade_academica.sql
> +    genero                  char(1)     NOT NULL,
Não vimos essa definição de GENERO, vou mudar de volta para o tipo gênero.

2023-08-04 01:05 UTC, Lvght approved these changes

2023-08-04 01:05 UTC, merged