Update professor_isf.sql
Lvght/e-andifes pull request #7
Opened 2023-08-02 12:38 UTC by lsr94

Credenciamento de Professores ISF

2023-08-02 12:57 UTC, Mobuos approved these changes
Confio

2023-08-02 13:02 UTC, Mobuos submitted a review, later dismissed

2023-08-02 14:24 UTC, MiguelChinellato approved these changes

2023-08-02 18:38 UTC, Alynva approved these changes
Parece bom

2023-08-02 18:39 UTC, Alynva commented on sql/professor_isf.sql
> +    		REFERENCES ficha_base
Resolvido

2023-08-02 19:47 UTC, Mobuos submitted a review, later dismissed

2023-08-02 19:47 UTC, MiguelChinellato approved these changes

2023-08-02 19:57 UTC, CarlosFontaneli submitted a review, later dismissed

2023-08-03 00:11 UTC, JonathanBDias submitted a review, later dismissed

2023-08-03 00:24 UTC, Lvght requested changes
Além da alteração que eu mencionei no arquivo, o banco não está criando as tabelas (vide resultado dos testes). Peço que corrijam e peçam a review novamente.

2023-08-03 00:24 UTC, Lvght commented on sql/professor_isf.sql
> +    categoria VARCHAR(25) NOT NULL,
Como é dito que `categoria` só pode assumir dois valores, no estado atual é perfeitamente possível adicionar dados inválidos no banco. É preciso criar um tipo como enumerador da mesma maneira que fizemos com gênero (vide exemplo abaixo).

https://github.com/Lvght/e-andifes/blob/3a9fde3bf7d862754484fef574f9dde47326f979/sql/__tipos.sql#L3C1-L3C44

2023-08-03 21:05 UTC, Lvght approved these changes

2023-08-03 21:06 UTC, merged