Professor ISF + Repositório
Lvght/e-andifes pull request #9
Opened 2023-08-02 13:39 UTC by lsr94

2023-08-02 17:37 UTC, MiguelChinellato approved these changes

2023-08-02 17:53 UTC, Mobuos approved these changes

2023-08-02 19:18 UTC, Kommnenos approved these changes

2023-08-02 19:35 UTC, Mobuos submitted a review, later dismissed

2023-08-03 00:12 UTC, JonathanBDias submitted a review, later dismissed

2023-08-03 00:34 UTC, Lvght requested changes

2023-08-03 00:34 UTC, Lvght commented on sql/professor_isf_edita_repositorio.sql
> +		FOREIGN KEY (cursista)
A tabela cursista não existe. Por favor, adicionem ela e solicitem a review novamente. Se cursista não for do seu grupo, crie uma tabela apenas com o identificador.

2023-08-03 13:42 UTC, Lvght commented
# O que falta para essa PR?

1. Adicionar a tabela de cursista com a chave primária apenas.
2. Verificar se o arquivo `__create__.txt` está correto.
3. Verificar se passa nos testes; e
4. Validar o diagrama do banco de dados.

2023-08-03 21:44 UTC, Lvght approved these changes

2023-08-03 21:46 UTC, NataliaBachiega approved these changes

2023-08-03 21:47 UTC, merged